import { type Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import { type ReactNode } from 'react';
import { MdHome, MdLogin } from 'react-icons/md';
import { ToastContainer } from 'react-toastify';
import { SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/nextjs';
import { Navbar, NavbarItem } from '@heroui/navbar';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import { Provider } from '@/providers';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: {
    template: '%s | paopapaopao',
    default: 'Create Next App - paopapaopao',
  },
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
  modal: ReactNode;
};

const RootLayout = ({ children, modal }: Readonly<Props>): ReactNode => {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Navbar isBordered>
            <NavbarItem>
              <Link
                href='/'
                className='flex items-center gap-2'
              >
                <MdHome size={32} />
                Home
              </Link>
            </NavbarItem>

            <SignedIn>
              <UserButton />
            </SignedIn>
            <SignedOut>
              <div className='flex items-center gap-2'>
                <MdLogin size={32} />
                <SignInButton mode='modal' />
              </div>
            </SignedOut>
          </Navbar>
          {children}
          {modal}
          <ToastContainer autoClose={4000} />
          <ReactQueryDevtools />
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
